spring:
  application:
    name: slide-upload-management
  profiles:
    active: dev
  main:
    allow-bean-definition-overriding: true

  servlet:
    multipart:
      max-file-size: 20GB
      max-request-size: 20GB

  data:
    mongodb:
      uri: mongodb://localhost:27017/slideupload
      database: slideupload

  cloud:
    aws:
      s3:
        bucket: slide-upload-bucket
      region:
        static: us-west-2

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: slide-upload-group
      auto-offset-reset: earliest
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

server:
  port: 8080

logging:
  level:
    org:
      springframework: INFO
    com:
      example: DEBUG
  file:
    name: logs/slide-upload-management.log